// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI commands (migrate, db pull, studio) need a session-capable connection;
    // the transaction-mode pooler (DATABASE_URL) doesn't support that.
    url: process.env["DIRECT_URL"],
  },
});
